const APP_VERSION="7.3.9";
const DEFAULT_STATE={level:"A1",xp:0,completed:{},testHistory:[],examHistory:[],streak:1,lastStudy:null};
let state=loadState(),lessonSession=null,testSession=null,examSession=null,speechRec=null,timerHandle=null;

function validProgressState(value){
 if(!value||typeof value!=="object"||Array.isArray(value))return false;
 if(!["A1","A2","B1","B2"].includes(value.level))return false;
 for(const key of ["testHistory","examHistory","chatHistory"])if(key in value&&!Array.isArray(value[key]))return false;
 for(const key of ["completed","skills","srs","errors","elite","story","chatPrefs","dailyDictionary","dailyPacks","dailyProgress","generatedLessons","completedTopics","lexicalCandidates","chatThreads","chatMemories","wordFavorites"]){if(key in value&&(!value[key]||typeof value[key]!=="object"||Array.isArray(value[key])))return false;}
 for(const key of ["xp","streak"])if(key in value&&(!Number.isFinite(value[key])||value[key]<0))return false;
 for(const key of ["srs","dailyDictionary","dailyPacks","dailyProgress","generatedLessons","lexicalCandidates"]){if(key in value&&Object.values(value[key]).some(item=>!item||typeof item!=="object"||Array.isArray(item)))return false;}
 if(value.skills&&Object.values(value.skills).some(score=>!Number.isFinite(score)))return false;
 for(const key of ["testHistory","examHistory","chatHistory"]){if(value[key]?.some(item=>!item||typeof item!=="object"||Array.isArray(item)))return false;}
 if(value.chatThreads&&Object.values(value.chatThreads).some(thread=>!Array.isArray(thread)))return false;
 return true;
}
function loadState(){try{return {...DEFAULT_STATE,...JSON.parse(localStorage.getItem("ne2_state")||"{}")}}catch{return {...DEFAULT_STATE}}}
let storageWarningShown=false;
function saveState(){try{localStorage.setItem("ne2_state",JSON.stringify(state));storageWarningShown=false;return true}catch{if(!storageWarningShown){storageWarningShown=true;alert("Не удалось сохранить прогресс на устройстве. Освободи место и скачай резервную копию в разделе «Прогресс».")}return false}}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function escJs(s=""){return String(s).replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/\n/g," ")}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function pct(n,d){return d?Math.round(n/d*100):0}
function lessons(level){return COURSE.filter(x=>x.level===level)}
function completed(level){return lessons(level).filter(x=>state.completed[x.id]).length}
function levelProgress(level){return pct(completed(level),lessons(level).length)}
function totalProgress(){return pct(Object.keys(state.completed).length,COURSE.length)}
function lastTest(level){return [...state.testHistory].reverse().find(x=>x.level===level)}
function levelDesc(l){return {A1:"База: знакомство, дом, покупки, транспорт и здоровье.",A2:"Самостоятельная повседневная жизнь: работа, услуги, планы и мнение.",B1:"Связная речь: работа, официальные обращения, новости и аргументы.",B2:"Точная и нюансированная речь: формальный стиль, дискуссия и презентации."}[l]}
function touchStudy(){const t=new Date().toISOString().slice(0,10);if(state.lastStudy!==t){if(state.lastStudy){const d=Math.round((new Date(t)-new Date(state.lastStudy))/86400000);state.streak=d===1?(state.streak||0)+1:1}else state.streak=1;state.lastStudy=t;saveState()}}

function nav(active){const a=[["home","⌂","Главная"],["course","▤","Курс"],["tests","✓","Тесты"],["exam","★","Экзамен"],["progress","↗","Прогресс"]];return `<nav class="nav">${a.map(x=>`<button class="${active===x[0]?"active":""}" onclick="navigate('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join("")}</nav>`}
function shell(content,active="home"){document.getElementById("app").innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">N</span>Norsk Eventyr</div><div class="row"><span class="pill">${esc(state.level)}</span><span class="pill">${state.xp} XP</span></div></header>${content}${nav(active)}</div>`}
function navigate(view,data){stopTimer();if(view==="home")renderHome();if(view==="course")renderCourse(data||state.level);if(view==="lesson")startLesson(data);if(view==="tests")renderTests();if(view==="test")startTest(data||state.level);if(view==="exam")renderExamHome();if(view==="examrun")startExam(data||"A1-A2");if(view==="progress")renderProgress();scrollTo({top:0,behavior:"smooth"})}

function renderHome(){
 const next=COURSE.find(x=>x.level===state.level&&!state.completed[x.id])||lessons(state.level)[0],last=state.examHistory.at(-1);
 shell(`<section class="hero"><div class="card hero-main"><div class="eyebrow">Норвежский Bokmål · A1–B2</div><h1>Курс, тесты и экзаменационная практика.</h1><p class="muted">Чтение, аудирование, письмо и устная речь. Уже в первом задании можно написать свой ответ или сказать его в микрофон; AI проверит смысл и язык.</p><div class="row"><button class="btn" onclick="navigate('lesson','${next.id}')">Продолжить: ${esc(next.title)}</button><button class="btn ghost" onclick="navigate('tests')">Тест уровня</button></div></div>
 <div class="card"><div class="metric"><span>Общий прогресс</span><strong>${totalProgress()}%</strong></div><div class="progress"><i style="width:${totalProgress()}%"></i></div><div class="metric"><span>Серия</span><strong>${state.streak} дн.</strong></div><div class="metric"><span>Уроки</span><strong>${Object.keys(state.completed).length}/${COURSE.length}</strong></div><div class="metric"><span>Последний экзамен</span><strong>${last?last.score+"%":"—"}</strong></div></div></section>
 <div class="section-title"><div><div class="eyebrow">Маршрут</div><h2>Уровни</h2></div></div>
 <section class="grid">${LEVELS.map(l=>`<article class="card level-card"><div class="row"><span class="level-badge">${l}</span><span class="tag">${completed(l)}/${lessons(l).length} уроков</span></div><div class="big">${l}</div><p class="muted">${levelDesc(l)}</p><div class="progress"><i style="width:${levelProgress(l)}%"></i></div><br><button class="btn secondary" onclick="state.level='${l}';saveState();navigate('course','${l}')">Открыть уровень</button></article>`).join("")}</section>
 <div class="section-title"><h2>Форматы практики</h2></div><section class="grid3"><article class="card mode-card"><div class="big">🧠</div><h3>AI-проверка</h3><p class="muted">Смысл, грамматика, словарь, связность и исправленный вариант.</p></article><article class="card mode-card"><div class="big">🎧</div><h3>Аудирование</h3><p class="muted">Норвежская речь и задания на понимание.</p></article><article class="card mode-card"><div class="big">🎤</div><h3>Устная речь</h3><p class="muted">Микрофон распознаёт ответ, AI оценивает содержание языка.</p></article></section>`,"home")
}

function renderCourse(level=state.level){
 state.level=level;saveState();const ls=lessons(level);
 shell(`<div class="screen-head"><button class="back" onclick="navigate('home')">←</button><div><div class="eyebrow">Курс ${level}</div><h2 style="margin:0">${levelDesc(level)}</h2></div></div>
 <div class="row">${LEVELS.map(l=>`<button class="btn ${l===level?"":"ghost"}" onclick="renderCourse('${l}')">${l}</button>`).join("")}</div>
 <div class="card" style="margin-top:14px"><div class="metric"><span>Прогресс</span><strong>${levelProgress(level)}%</strong></div><div class="progress"><i style="width:${levelProgress(level)}%"></i></div></div>
 <div class="section-title"><h2>Уроки</h2><span class="tag">6 заданий каждый</span></div><section class="lesson-list">${ls.map((x,i)=>`<article class="card lesson-card ${state.completed[x.id]?"done":""}"><div class="lesson-num">${state.completed[x.id]?"✓":i+1}</div><div><h3>${x.icon} ${esc(x.title)}</h3><div class="meta">${esc(x.grammar)} · словарь · аудирование · чтение · письмо · речь</div></div><button class="btn ${state.completed[x.id]?"secondary":""}" onclick="navigate('lesson','${x.id}')">${state.completed[x.id]?"Повторить":"Начать"}</button></article>`).join("")}</section>`,"course")
}

function startLesson(id){const l=COURSE.find(x=>x.id===id);if(!l)return navigate("course");state.level=l.level;saveState();touchStudy();lessonSession={lesson:l,step:0,locked:false};renderLesson()}
function renderLesson(){const s=lessonSession,l=s.lesson,n=["Фраза","Словарь","Аудирование","Чтение","Письмо","Речь"];let b="";if(s.step===0)b=lessonIntro(l);if(s.step===1)b=vocabEx(l);if(s.step===2)b=listenEx(l);if(s.step===3)b=readEx(l);if(s.step===4)b=freeEx(l,"writing");if(s.step===5)b=freeEx(l,"speaking");
 shell(`<div class="lesson-head-v6"><button class="back-v6" onclick="navigate('course','${l.level}')">←</button><div><small>${l.level} · ${esc(l.title)}</small><b>${n[s.step]}</b></div><span>${s.step+1}/6</span></div><div class="progress lesson-progress-v6"><i style="width:${pct(s.step+1,6)}%"></i></div><section class="exercise lesson-exercise-v6">${b}</section>`,"course")}
const INTRODUCTION_DIALOGUE=[
 {phrase:"Hei! Jeg heter Nora. Hva heter du?",ru:"Привет! Меня зовут Нора. Как тебя зовут?",goal:"Поздоровайся и назови своё имя."},
 {phrase:"Hyggelig å møte deg! Hvor kommer du fra?",ru:"Приятно познакомиться! Откуда ты?",goal:"Скажи, из какой страны или города ты родом."},
 {phrase:"Hvor bor du nå?",ru:"Где ты сейчас живёшь?",goal:"Скажи, где ты сейчас живёшь."},
 {phrase:"Hva gjør du til daglig? Jobber du, eller lærer du norsk?",ru:"Чем ты занимаешься каждый день? Работаешь или учишь норвежский?",goal:"Расскажи о работе или изучении норвежского. Оба варианта допустимы."},
 {phrase:"Nå er det din tur. Still meg et spørsmål for å bli kjent med meg.",ru:"Теперь твоя очередь. Задай мне вопрос, чтобы познакомиться со мной.",goal:"Задай собеседнице один простой вопрос о её имени, происхождении, месте жительства или работе."}
];
function currentDialogueTurn(l){
 if(l.id!=="a1-1")return {phrase:l.phrase,ru:l.ru,goal:"Естественно ответить собеседнику своими словами по-норвежски."};
 const i=lessonSession.dialogueIndex||0;
 return {...INTRODUCTION_DIALOGUE[i],dialogueLabel:"Знакомство с Норой · "+(i+1)+"/"+INTRODUCTION_DIALOGUE.length};
}
function lessonIntro(l){const turn=currentDialogueTurn(l);const shown={...l,...turn};l=shown;return `<article class="card lesson-intro-v6"><div class="phrase-v6"><small>${l.dialogueLabel||"Фраза"}</small><div class="prompt">${esc(l.phrase)}</div><div class="phrase-actions-v6"><button onclick="speakText('${escJs(l.phrase)}',.82)">🔊 Фраза</button><button onclick="toggle('tr')">RU Перевод</button></div><div id="tr" class="translation compact-translation-v6" style="display:none">${esc(l.ru)}</div></div><div class="lesson-words-v6">${l.vocab.map(v=>`<span><b>${esc(v[0])}</b><small>${esc(v[1])}</small></span>`).join("")}</div><div class="answer-label-v6"><b>Твой ответ</b><span>текстом или голосом</span></div><textarea id="dialogAnswer" class="input lesson-answer-v6" rows="2" placeholder="Напиши по-норвежски…"></textarea><div class="lesson-actions-v6"><button id="micBtn" class="btn secondary" onclick="toggleMic('dialogAnswer','','${escJs(l.phrase)}')">🎤 Сказать</button><button class="btn" onclick="checkDialogue()">✓ Проверить</button></div><div id="dialogFb"></div><details class="grammar-fold-v6"><summary>Грамматика</summary><p>${esc(l.grammar)}</p></details></article>`}
async function checkDialogue(){
 const s=lessonSession,input=document.getElementById("dialogAnswer"),a=input?.value.trim();if(!a||s.locked)return;
 const l=s.lesson,turn=currentDialogueTurn(l),b=document.getElementById("dialogFb");s.locked=true;
 b.innerHTML='<div class="feedback">Проверяю…</div>';
 const r=await aiEvaluate({answer:a,question:turn.phrase,goal:turn.goal,level:l.level,mode:"dialogue"});
 if(!b.isConnected||lessonSession!==s){s.locked=false;return;}
 if(!r.ok){s.locked=false;b.innerHTML='<div class="feedback bad">Проверка временно недоступна. Попробуй ещё раз.</div>';return;}
 const d=r.data,ok=d.accepted!==false&&(d.score??70)>=55;
 if(ok){
  b.innerHTML='<div class="feedback good"><b>✓ Верно</b></div>';
  neAdvance(()=>{
   if(l.id==="a1-1"&&(s.dialogueIndex||0)<INTRODUCTION_DIALOGUE.length-1){
    s.dialogueIndex=(s.dialogueIndex||0)+1;state.xp+=10;saveState();s.locked=false;renderLesson();
   }else lessonNext(10);
  },450);return;
 }
 s.locked=false;b.innerHTML='<div class="feedback bad"><b>Попробуй ещё раз</b><br>'+esc(d.explanation_ru||"Исправь ответ и проверь снова.")+(d.corrected?'<br><b>Подсказка:</b> '+esc(d.corrected):"")+'</div>';input.focus();
}

function vocabEx(l){const t=l.vocab[0],pool=COURSE.filter(x=>x.level===l.level).flatMap(x=>x.vocab.map(v=>v[1])).filter(x=>x!==t[1]),o=shuffle([t[1],...shuffle(pool).slice(0,3)]),c=o.indexOf(t[1]);return `<article class="card"><div class="eyebrow">Словарь</div><div class="prompt">Что значит «${esc(t[0])}»?</div><div class="choice-list">${o.map((x,i)=>`<button class="choice" onclick="lessonChoice(this,${i},${c},'${escJs(t[0]+" = "+t[1])}')">${esc(x)}</button>`).join("")}</div><div id="fb"></div></article>`}
function listenEx(l){const d=shuffle(COURSE.filter(x=>x.level===l.level&&x.id!==l.id)).slice(0,3).map(x=>x.phrase),o=shuffle([l.phrase,...d]),c=o.indexOf(l.phrase);return `<article class="card"><div class="eyebrow">Аудирование</div><div class="prompt">Прослушай и выбери точную фразу.</div><button class="btn" onclick="speakText('${escJs(l.phrase)}',.78)">▶ Прослушать</button><div class="choice-list">${o.map((x,i)=>`<button class="choice" onclick="lessonChoice(this,${i},${c},'${escJs(l.ru)}')">${esc(x)}</button>`).join("")}</div><div id="fb"></div></article>`}
function readEx(l){return `<article class="card"><div class="eyebrow">Чтение</div><div class="translation">${esc(l.read)}</div><div class="prompt">${esc(l.q)}</div><div class="choice-list">${l.opts.map((x,i)=>`<button class="choice" onclick="lessonChoice(this,${i},${l.correct},'Ответ находится в тексте.')">${esc(x)}</button>`).join("")}</div><div id="fb"></div></article>`}
function lessonChoice(btn,i,c,note){if(lessonSession.locked)return;const ok=i===c;const buttons=[...document.querySelectorAll(".choice")];if(ok){lessonSession.locked=true;buttons.forEach((b,j)=>{b.disabled=true;if(j===c)b.classList.add("good")});document.getElementById("fb").innerHTML='<div class="feedback good"><b>✓ Верно</b></div>';neAdvance(()=>lessonNext(15),420);return}btn.classList.add("bad");btn.disabled=true;document.getElementById("fb").innerHTML='<div class="feedback bad"><b>Неверно.</b> '+esc(note)+'<br><small>Выбери другой вариант.</small></div>';lessonSession.locked=false}
function freeEx(l,mode){const sp=mode==="speaking",p=sp?l.speaking:l.writing;return `<article class="card"><div class="eyebrow">${sp?"Устная речь":"Письмо"} · AI</div><div class="prompt">${esc(p)}</div>${sp?'<div class="notice">Нажми микрофон и говори по-норвежски. Можно также ввести ответ.</div>':""}<textarea id="freeAnswer" class="input" placeholder="Ответ по-норвежски…"></textarea><div class="row" style="margin-top:10px">${sp?'<button id="micBtn" class="btn secondary" onclick="toggleMic()">🎤 Говорить</button>':""}<button class="btn" onclick="checkFree('${mode}')">🧠 Проверить AI</button></div><div id="freeFb"></div></article>`}
async function checkFree(mode){const a=document.getElementById("freeAnswer").value.trim();if(!a)return;const b=document.getElementById("freeFb"),l=lessonSession.lesson,p=mode==="speaking"?l.speaking:l.writing;b.innerHTML='<div class="feedback">Проверяю…</div>';const r=await aiEvaluate({answer:a,question:p,goal:p,level:l.level,mode});if(!r.ok){b.innerHTML='<div class="feedback bad">Проверка временно недоступна. Попробуй ещё раз.</div>';return}const d=r.data,ok=d.accepted!==false&&(d.score??70)>=55;if(ok){b.innerHTML='<div class="feedback good"><b>✓ Хороший ответ</b></div>';neAdvance(()=>lessonNext(20),500);return}b.innerHTML='<div class="feedback bad"><b>Исправь и попробуй ещё раз</b><br>'+esc(d.explanation_ru||"")+(d.corrected?'<br><br><b>Возможный вариант:</b><br>'+esc(d.corrected):"")+'</div>';document.getElementById("freeAnswer")?.focus()}
function lessonNext(xp=0){state.xp+=xp;saveState();lessonSession.step++;lessonSession.locked=false;if(lessonSession.step>5)return finishLesson();renderLesson()}
function finishLesson(){const l=lessonSession.lesson,first=!state.completed[l.id];state.completed[l.id]=true;if(first)state.xp+=40;const today=new Date().toLocaleDateString("sv-SE");state.guidedJourney=state.guidedJourney||{lessonDates:{},reviewDates:{}};state.guidedJourney.lessonDates=state.guidedJourney.lessonDates||{};state.guidedJourney.lessonDates[today]=l.id;saveState();shell(`<section class="card guided-finish-v61"><div class="guided-finish-mark-v61">✓</div><div class="eyebrow">${l.level} · готово на сегодня</div><h1>${esc(l.title)}</h1><p class="muted">Урок засчитан в сегодняшний маршрут.</p><button class="btn" onclick="navigate('home')">Продолжить день →</button><button class="btn ghost" onclick="navigate('course','${l.level}')">К курсу</button></section>`,"home")}

function renderTests(){shell(`<div class="screen-head"><button class="back" onclick="navigate('hub')">←</button><div><div class="eyebrow">Контроль знаний</div><h2 style="margin:0">Тесты по уровням</h2></div></div><div class="notice">Лексика, грамматика, чтение и аудирование, плюс отдельные свободные задания на письмо и устную речь с AI-проверкой.</div><section class="grid" style="margin-top:14px">${LEVELS.map(l=>{const t=lastTest(l);return `<article class="card"><div style="font-size:34px;font-weight:950">${l}</div><p class="muted">${levelDesc(l)}</p><div class="metric"><span>Последний результат</span><strong>${t?t.score+"%":"—"}</strong></div><button class="btn" onclick="navigate('test','${l}')">${t?"Пройти снова":"Начать тест"}</button></article>`}).join("")}</section>`,"tests")}
function buildTest(level){const ls=lessons(level),q=[];ls.forEach(l=>q.push({type:"mc",text:l.q,context:l.read,opts:l.opts,correct:l.correct}));GRAMMAR[level].forEach(g=>q.push({type:"mc",text:g[0],opts:g.slice(1,5),correct:g[5],note:g[6]}));const l=ls[Math.floor(Math.random()*ls.length)],o=shuffle([l.phrase,...shuffle(ls.filter(x=>x.id!==l.id)).slice(0,3).map(x=>x.phrase)]);q.push({type:"listen",text:"Прослушай и выбери точную фразу.",audio:l.phrase,opts:o,correct:o.indexOf(l.phrase)});q.push({type:"free",mode:"writing",text:l.writing});q.push({type:"free",mode:"speaking",text:l.speaking});return q}
function startTest(level){touchStudy();state.level=level;saveState();testSession={level,questions:buildTest(level),i:0,correct:0,freeScores:[]};renderTest()}
function renderTest(){const s=testSession,q=s.questions[s.i];if(!q)return finishTest();const obj=q.type!=="free";shell(`<div class="screen-head"><button class="back" onclick="navigate('tests')">←</button><div><div class="eyebrow">Тест ${s.level}</div><h2 style="margin:0">Вопрос ${s.i+1}/${s.questions.length}</h2></div></div><div class="progress"><i style="width:${pct(s.i,s.questions.length)}%"></i></div><section class="exercise"><article class="card">${q.context?`<div class="translation">${esc(q.context)}</div><br>`:""}<div class="prompt">${esc(q.text)}</div>${q.type==="listen"?`<button class="btn" onclick="speakText('${escJs(q.audio)}',.8)">▶ Прослушать</button>`:""}${obj?`<div class="choice-list">${q.opts.map((x,i)=>`<button class="choice" onclick="answerTest(${i})">${esc(x)}</button>`).join("")}</div>`:`<div class="eyebrow">${q.mode==="speaking"?"Устная речь":"Письмо"} · свободный ответ</div><textarea id="testFree" class="input" placeholder="${q.mode==="speaking"?"Скажи ответ в микрофон или введи текст…":"Напиши ответ по-норвежски…"}"></textarea><div class="row" style="margin-top:10px">${q.mode==="speaking"?'<button id="micBtn" class="btn secondary" onclick="toggleMic(\'testFree\')">🎤 Ответить голосом</button>':""}<button class="btn" onclick="answerTestFree()">🧠 Проверить мой ответ</button></div>`}<div id="testFb"></div></article></section>`,"tests")}
function answerTest(i){const q=testSession.questions[testSession.i],ok=i===q.correct;if(ok)testSession.correct++;document.querySelectorAll(".choice").forEach((b,j)=>{b.disabled=true;if(j===q.correct)b.classList.add("good");if(j===i&&!ok)b.classList.add("bad")});document.getElementById("testFb").innerHTML='<div class="feedback '+(ok?"good":"bad")+'">'+(ok?"✓ Верно":"Неверно")+(q.note?" · "+esc(q.note):"")+'</div>';neAdvance(()=>testNext(),ok?380:900)}
async function answerTestFree(){const q=testSession.questions[testSession.i],a=document.getElementById("testFree").value.trim();if(!a)return;const b=document.getElementById("testFb");b.innerHTML='<div class="feedback">Оцениваю…</div>';const r=await aiEvaluate({answer:a,question:q.text,goal:q.text,level:testSession.level,mode:"test_"+(q.mode||"writing")});if(r.ok){const pts=Math.max(0,Math.min(1,(r.data.score||0)/100));testSession.freeScores.push(pts);b.innerHTML='<div class="feedback '+(pts>=.55?"good":"bad")+'">'+esc(r.data.explanation_ru||"Оценено.")+(r.data.corrected?'<br><b>Лучше:</b> '+esc(r.data.corrected):"")+'</div>';neAdvance(()=>testNext(),pts>=.55?500:1100)}else{testSession.freeScores.push(null);b.innerHTML='<div class="feedback bad">AI недоступен; ответ не учитывается.</div>';neAdvance(()=>testNext(),900)}}
function testNext(){testSession.i++;renderTest()}
function finishTest(){const obj=testSession.questions.filter(x=>x.type!=="free").length,validFree=testSession.freeScores.filter(x=>x!==null),freeSum=validFree.reduce((a,b)=>a+b,0),den=obj+validFree.length,score=den?Math.round((testSession.correct+freeSum)/den*100):0;state.testHistory.push({level:testSession.level,score,date:new Date().toISOString()});state.xp+=Math.round(score/5);saveState();const m=score>=80?"Уверенный результат":score>=60?"Рабочий уровень, есть пробелы":"Нужно повторить основные темы";shell(`<section class="card" style="max-width:680px;margin:40px auto;text-align:center"><div class="score-ring" style="--pct:${score}%"><b>${score}%</b></div><br><div class="eyebrow">Тест ${testSession.level}</div><h1>${m}</h1><p class="muted">Тест включал выбор ответа, письмо и устную речь. Это учебный результат приложения, не официальный уровень Norskprøven.</p><div class="row" style="justify-content:center"><button class="btn" onclick="navigate('course','${testSession.level}')">К курсу</button><button class="btn secondary" onclick="navigate('tests')">Все тесты</button></div></section>`,"tests")}

function renderExamHome(){const c=[["A1-A2","Базовый диапазон"],["A2-B1","Средний диапазон"],["B1-B2","Продвинутый диапазон"]];shell(`<div class="screen-head"><button class="back" onclick="navigate('home')">←</button><div><div class="eyebrow">Тренировочный экзамен</div><h2 style="margin:0">Симулятор Norskprøven</h2></div></div><div class="notice"><b>Важно:</b> это учебный симулятор, не официальный экзамен. Он тренирует четыре части: чтение, аудирование, письмо и устную речь.</div><section class="grid" style="margin-top:14px">${c.map(x=>`<article class="card"><span class="level-badge">${x[0]}</span><h2>${x[1]}</h2><div class="row"><span class="tag">📖 Чтение</span><span class="tag">🎧 Аудирование</span><span class="tag">✍️ Письмо</span><span class="tag">🎤 Речь</span></div><br><button class="btn" onclick="navigate('examrun','${x[0]}')">Начать экзамен</button></article>`).join("")}</section><p class="muted" style="margin-top:14px">Официальная Norskprøven имеет четыре отдельные части; чтение и аудирование адаптивны, а для письма и устной части выбирается диапазон уровня. Здесь используется уменьшенная тренировочная модель, а не копия официальных заданий.</p>`,"exam")}
function startExam(band){touchStudy();const b=EXAM_BANK[band];examSession={band,section:0,i:0,objScore:0,objTotal:0,ai:[],remaining:3600,sections:[{name:"Чтение",type:"objective",items:b.reading.map(x=>({context:x[0],q:x[1],opts:x[2],correct:x[3]}))},{name:"Аудирование",type:"listening",items:b.listening.map(x=>({audio:x[0],q:"Выбери наиболее точный смысл.",opts:x[1],correct:x[2]}))},{name:"Письмо",type:"writing",items:b.writing.map(q=>({q}))},{name:"Устная речь",type:"speaking",items:b.speaking.map(q=>({q}))}]};startTimer();renderExam()}
function renderExam(){const s=examSession,sec=s.sections[s.section];if(!sec)return finishExam();const it=sec.items[s.i];if(!it){s.section++;s.i=0;return renderExam()}const obj=sec.type==="objective"||sec.type==="listening";shell(`<div class="screen-head"><button class="back" onclick="exitExam()">←</button><div style="flex:1"><div class="eyebrow">${s.band} · симулятор</div><h2 style="margin:0">${sec.name} ${s.i+1}/${sec.items.length}</h2></div><span id="timer" class="pill timer"></span></div><div class="exam-stepper">${s.sections.map((x,i)=>`<span class="exam-step ${i===s.section?"active":""}">${i+1}. ${x.name}</span>`).join("")}</div><section class="exercise"><article class="card">${it.context?`<div class="translation">${esc(it.context)}</div><br>`:""}${sec.type==="listening"?`<button class="btn" onclick="speakText('${escJs(it.audio)}',.86)">▶ Прослушать</button><br><br>`:""}<div class="prompt">${esc(it.q)}</div>${obj?`<div class="choice-list">${it.opts.map((x,i)=>`<button class="choice" onclick="answerExamObj(${i})">${esc(x)}</button>`).join("")}</div>`:`<textarea id="examFree" class="input" placeholder="Ответ по-норвежски…"></textarea><div class="row" style="margin-top:10px">${sec.type==="speaking"?'<button id="micBtn" class="btn secondary" onclick="toggleMic(\'examFree\')">🎤 Говорить</button>':""}<button class="btn" onclick="answerExamFree('${sec.type}')">Сдать ответ</button></div>`}<div id="examFb"></div></article></section>`,"exam");updateTimer()}
function answerExamObj(i){const s=examSession,it=s.sections[s.section].items[s.i];s.objTotal++;if(i===it.correct)s.objScore++;s.i++;renderExam()}
async function answerExamFree(mode){const a=document.getElementById("examFree").value.trim();if(!a)return;const s=examSession,it=s.sections[s.section].items[s.i],b=document.getElementById("examFb");b.innerHTML='<div class="feedback">🧠 Экзаменационная AI-оценка…</div>';const r=await aiEvaluate({answer:a,question:it.q,goal:it.q,level:s.band.split("-")[1],mode:"exam_"+mode}),score=r.ok?Math.max(0,Math.min(100,r.data.score||0)):0;s.ai.push(score);b.innerHTML=`<div class="feedback ${score>=55?"good":"bad"}">${r.ok?`<b>${score}/100</b> · ${esc(r.data.explanation_ru||"")}`:"AI не ответил; задание не оценено."}</div><button class="btn" style="width:100%;margin-top:10px" onclick="examNext()">Следующее →</button>`}
function examNext(){examSession.i++;renderExam()}
function finishExam(){stopTimer();const s=examSession,obj=pct(s.objScore,s.objTotal),ai=s.ai.length?Math.round(s.ai.reduce((a,b)=>a+b,0)/s.ai.length):0,score=Math.round(obj*.5+ai*.5),m=score>=80?"Высокая учебная готовность":score>=65?"Средняя учебная готовность":"Нужно продолжить подготовку";state.examHistory.push({band:s.band,score,obj,ai,date:new Date().toISOString()});state.xp+=Math.round(score/3);saveState();shell(`<section class="card" style="max-width:760px;margin:28px auto"><div class="eyebrow">${s.band} · результат симулятора</div><div class="grid"><div><div class="score-ring" style="--pct:${score}%"><b>${score}%</b></div></div><div><h1 style="font-size:34px">${m}</h1><p class="muted">Не официальный балл и не присвоение уровня.</p><div class="metric"><span>Чтение + аудирование</span><strong>${obj}%</strong></div><div class="metric"><span>Письмо + речь (AI)</span><strong>${ai}%</strong></div></div></div><hr><div class="row"><button class="btn" onclick="navigate('exam')">Другой экзамен</button><button class="btn secondary" onclick="navigate('course','${s.band.split("-")[1]}')">Тренироваться</button></div></section>`,"exam")}
function exitExam(){if(confirm("Завершить экзамен без результата?"))navigate("exam")}

function renderProgress(){const t=state.testHistory.slice(-8).reverse(),e=state.examHistory.slice(-6).reverse();shell(`<div class="screen-head"><button class="back" onclick="navigate('hub')">←</button><div><div class="eyebrow">Статистика</div><h2 style="margin:0">Твой прогресс</h2></div></div><section class="grid3"><div class="kpi"><small>XP</small><strong>${state.xp}</strong></div><div class="kpi"><small>Уроки</small><strong>${Object.keys(state.completed).length}/${COURSE.length}</strong></div><div class="kpi"><small>Серия</small><strong>${state.streak} дн.</strong></div></section><div class="section-title"><h2>По уровням</h2></div><section class="grid">${LEVELS.map(l=>`<article class="card"><div class="row"><span class="level-badge">${l}</span><strong>${levelProgress(l)}%</strong></div><br><div class="progress"><i style="width:${levelProgress(l)}%"></i></div></article>`).join("")}</section><div class="section-title"><h2>История тестов</h2></div><section class="card">${t.length?`<table class="table"><tr><th>Уровень</th><th>Результат</th><th>Дата</th></tr>${t.map(x=>`<tr><td>${x.level}</td><td>${x.score}%</td><td>${new Date(x.date).toLocaleDateString("ru-RU")}</td></tr>`).join("")}</table>`:'<div class="empty">Тестов пока нет.</div>'}</section><div class="section-title"><h2>История экзаменов</h2></div><section class="card">${e.length?`<table class="table"><tr><th>Диапазон</th><th>Итог</th><th>Дата</th></tr>${e.map(x=>`<tr><td>${x.band}</td><td>${x.score}%</td><td>${new Date(x.date).toLocaleDateString("ru-RU")}</td></tr>`).join("")}</table>`:'<div class="empty">Экзаменов пока нет.</div>'}</section><button class="btn red" onclick="resetProgress()">Сбросить прогресс</button>`,"progress")}
function resetProgress(){if(confirm("Удалить весь прогресс?")){localStorage.setItem("ne2_state_before_reset",JSON.stringify(state));localStorage.removeItem("ne2_state");localStorage.removeItem("ne_cloud_link");location.reload()}}

async function aiEvaluate(payload){try{const r=await fetch("/api/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));return r.ok?{ok:true,data:d}:{ok:false,error:d.code||d.error||("HTTP "+r.status)}}catch{return {ok:false,error:"NETWORK"}}}
function speakText(text,rate=.85){if(!("speechSynthesis" in window))return alert("Синтез речи не поддерживается.");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="nb-NO";u.rate=rate;const v=speechSynthesis.getVoices().find(x=>/^nb|no/i.test(x.lang));if(v)u.voice=v;speechSynthesis.speak(u)}
function toggleMic(target="freeAnswer"){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert("Распознавание речи недоступно. Используй Chrome и разреши микрофон.");if(speechRec){speechRec.stop();return}speechRec=new SR();speechRec.lang="nb-NO";speechRec.interimResults=true;const btn=document.getElementById("micBtn"),f=document.getElementById(target);speechRec.onstart=()=>{if(btn)btn.textContent="■ Слушаю…"};speechRec.onresult=e=>{let t="";for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;f.value=t};speechRec.onerror=e=>alert("Ошибка микрофона: "+e.error);speechRec.onend=()=>{speechRec=null;if(btn)btn.textContent="🎤 Говорить"};speechRec.start()}
function toggle(id){const e=document.getElementById(id);e.style.display=e.style.display==="none"?"block":"none"}
function startTimer(){stopTimer();timerHandle=setInterval(()=>{if(!examSession)return;examSession.remaining--;updateTimer();if(examSession.remaining<=0)finishExam()},1000)}
function updateTimer(){const e=document.getElementById("timer");if(!e||!examSession)return;const m=Math.floor(examSession.remaining/60),s=examSession.remaining%60;e.textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}

Object.assign(window,{navigate,renderCourse,lessonNext,lessonChoice,checkDialogue,checkFree,speakText,toggle,toggleMic,answerTest,answerTestFree,testNext,answerExamObj,answerExamFree,examNext,exitExam,resetProgress});
renderHome();
// Service worker registration and update notices are handled by updates.js.