const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');let calls=0;
const server=http.createServer(async(req,res)=>{
 const name=new URL(req.url,'http://localhost').pathname;
 if(name.startsWith('/api/')){let data='';for await(const c of req)data+=c;const body=JSON.parse(data||'{}');let out={score:90,accepted:true,explanation_ru:'Хорошо',reply_no:'Hei! Hvordan har du det?',translation_ru:'Привет',text:'Jeg bor i Norge.'};if(name.endsWith('session'))out={token:'qa'};if(name.endsWith('evaluate')){calls++;if(body.action==='lexical_gap')out={candidates:[]};await new Promise(r=>setTimeout(r,120))}if(name.endsWith('generate')){out={};await new Promise(r=>setTimeout(r,120))}if(name.endsWith('drill')){out={items:[{audio_no:'Hei',translation_ru:'Привет'}]};await new Promise(r=>setTimeout(r,120))}res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(out))}
 try{const file=path.join(root,name==='/'?'index.html':name);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.webp':'image/webp','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('not found')}
});

(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({...(process.env.NE_CHROMIUM_PATH?{executablePath:process.env.NE_CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const page=await browser.newPage({serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForTimeout(350);
 let transcriptionCalls=0,questionCalls=0;
 await page.route('**/api/transcribe',async r=>{transcriptionCalls++;await new Promise(resolve=>setTimeout(resolve,200));await r.fulfill({json:{text:'Jeg bor i Norge og jeg jobber i en butikk hver dag.'}})});
 await page.route('**/api/listening-questions',async r=>{questionCalls++;await r.fulfill({json:{questions:[{q:'Где?',opts:['Norge','Sverige','Danmark','Finland'],correct:0}],vocabulary:[]}})});
 const file={name:'test.wav',mimeType:'audio/wav',buffer:Buffer.from('QA audio')};
 await page.evaluate(()=>navigate('listeninglab'));await page.locator('#listenFile').setInputFiles(file);await page.evaluate(()=>{analyzeListeningFile();analyzeListeningFile()});await page.waitForSelector('#listenQfb',{state:'attached'});assert.equal(transcriptionCalls,1);assert.equal(questionCalls,1);console.log('PASS uploaded audio analyzed once');
 await page.evaluate(()=>navigate('listeninglab'));await page.locator('#listenFile').setInputFiles(file);await page.evaluate(()=>analyzeListeningFile()&&undefined);await page.evaluate(()=>navigate('course'));await page.waitForTimeout(400);assert(await page.locator('.course-map-v7').count());assert.equal(questionCalls,1);console.log('PASS late transcription cannot replace another screen or generate needless questions');
 await page.evaluate(()=>navigate('listeninglab'));await page.locator('#listenFile').setInputFiles(file);await page.evaluate(async()=>{const original=FileReader.prototype.readAsDataURL;FileReader.prototype.readAsDataURL=function(){this.onerror()};try{await analyzeListeningFile()}finally{FileReader.prototype.readAsDataURL=original}});assert((await page.locator('#listenLabBox').innerText()).includes('Не удалось прочитать'));await page.evaluate(()=>analyzeListeningFile());await page.waitForSelector('#listenQfb',{state:'attached'});assert.equal(questionCalls,2);console.log('PASS file read error handled and retry succeeds');
 let dailyCalls=0;await page.route('**/api/daily',async r=>{dailyCalls++;await new Promise(resolve=>setTimeout(resolve,180));await r.fulfill({json:{words:[],practice:[],review_words:[]}})});
 await page.evaluate(()=>{state.level='A1';delete state.dailyPacks[neLocalDate()];navigate('daily');generateDailyPack();generateDailyPack();navigate('course','B2')});await page.waitForTimeout(400);assert.equal(dailyCalls,1);assert(await page.evaluate(()=>state.level==='B2'&&state.dailyPacks[neLocalDate()].level==='A1'&&!!document.querySelector('.course-map-v7')));console.log('PASS daily generation sent once, retains requested level and preserves navigation');
 await page.evaluate(()=>{startExamPart('listening');window.qaResolve=[];window.qaOriginalSpeak=speakText;speakText=window.speakText=()=>new Promise(resolve=>qaResolve.push(resolve));playExamAudio();playExamAudio();answerExamObjectiveV3(0);qaResolve.forEach(resolve=>resolve())});await page.waitForTimeout(50);assert.equal(await page.locator('#examAudioBtn').isDisabled(),false);await page.evaluate(()=>speakText=window.speakText=qaOriginalSpeak);console.log('PASS late speech cannot disable next question audio');
 assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
