const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');let calls=0;
const server=http.createServer(async(req,res)=>{
 const name=new URL(req.url,'http://localhost').pathname;
 if(name.startsWith('/api/')){let data='';for await(const c of req)data+=c;const body=JSON.parse(data||'{}');let out={score:90,accepted:true,explanation_ru:'Хорошо',reply_no:'Hei! Hvordan har du det?',translation_ru:'Привет',text:'Jeg bor i Norge.'};if(name.endsWith('session')&&body.action)out={status:'approved',access_granted:true,owner:true,user_id:'11111111-1111-4111-8111-111111111111',email:'owner@example.com'};if(name.endsWith('session')&&!body.action)out={token:'qa'};if(name.endsWith('evaluate')){calls++;if(body.action==='lexical_gap')out={candidates:[]};await new Promise(r=>setTimeout(r,120))}if(name.endsWith('generate')){out={title:'QA adaptive lesson',grammarTitle:'Presens',grammarRuleRu:'Глагол в настоящем времени.',grammarExamples:['Jeg jobber.','Du bor her.','Vi lærer norsk.'],grammarQ:'Velg riktig setning.',grammarOpts:['Jeg jobber i dag.','Jeg jobbe i dag.','Jeg jobbet i morgen.','Jeg å jobber.'],grammarCorrect:0,phrase:'Jeg jobber i dag.',ru:'Я работаю сегодня.',vocab:[['jobb','работа'],['i dag','сегодня'],['lære','учить'],['norsk','норвежский'],['bo','жить'],['her','здесь']],read:'Jeg heter Ola. Jeg jobber i dag.',q:'Hva gjør Ola i dag?',opts:['Han jobber.','Han sover.','Han reiser.','Han lager mat.'],correct:0,writing:'Skriv to setninger om dagen din.',speaking:'Fortell kort om dagen din.'};await new Promise(r=>setTimeout(r,120))}if(name.endsWith('drill')){out={items:[{audio_no:'Hei',translation_ru:'Привет'}]};await new Promise(r=>setTimeout(r,120))}res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(out))}
 try{const file=path.join(root,name==='/'?'index.html':name);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.webp':'image/webp','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('not found')}
});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({...(process.env.NE_CHROMIUM_PATH?{executablePath:process.env.NE_CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:390,height:844},serviceWorkers:'block'});let errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.NEAccess?.ready());
 for(const route of ['home','course','chat','story','hub','dictionary','daily','review','tests','exam','progress','plan','dictation','grammarlab','pronunciation','listeninglab','cloud','settings','storyjournal','storyside','teacher']){await page.evaluate(route=>navigate(route),route);await page.waitForTimeout(160);assert(await page.locator('#app main').innerText(),route);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),route+' overflow')}
 console.log('PASS 21 routes including adaptive teacher');
  await page.evaluate(()=>{state.level='A1';navigate('teacher')});assert((await page.locator('#app main').innerText()).includes('Нора ведёт занятие'));
  await page.evaluate(()=>teacherStartMission());await page.waitForTimeout(500);assert(await page.evaluate(()=>lessonSession?.lesson?._adaptive?.moduleId==='a1-foundation'));assert((await page.locator('#app main').innerText()).includes('QA adaptive lesson'));console.log('PASS adaptive teacher opens a generated mastery lesson');
 await page.evaluate(()=>{testSession={level:'A1',questions:[{type:'mc',text:'test',opts:['a','b','c','d'],correct:0},{type:'mc',text:'next',opts:['a','b','c','d'],correct:0}],i:0,correct:0,freeScores:[]};renderTest();answerTest(0);answerTest(0)});await page.waitForTimeout(600);assert(await page.evaluate(()=>testSession.i===1&&testSession.correct===1));
 let before=calls;await page.evaluate(()=>{testSession={level:'A1',questions:[{type:'free',mode:'writing',text:'Write'},{type:'free',mode:'writing',text:'Next'}],i:0,correct:0,freeScores:[]};renderTest();document.getElementById('testFree').value='Jeg bor her.';answerTestFree();answerTestFree()});await page.waitForTimeout(900);assert.equal(calls,before+1);assert(await page.evaluate(()=>testSession.i===1&&testSession.freeScores.length===1));
 await page.evaluate(()=>{document.getElementById('testFree').value='Jeg bor her.';answerTestFree();navigate('course')});await page.waitForTimeout(900);assert(await page.evaluate(()=>testSession.freeScores.length===1&&!!document.querySelector('.course-map-v7')));console.log('PASS duplicate answers and stale evaluation');
 await page.evaluate(()=>{navigate('test','A1');navigate('settings')});await page.waitForTimeout(500);assert((await page.locator('#app main').innerText()).includes('Профиль'));
 await page.evaluate(()=>{state.elite.drills={};navigate('dictation');navigate('course')});await page.waitForTimeout(500);assert(await page.locator('.course-map-v7').count());console.log('PASS generation preserves navigation');
 await page.evaluate(()=>{state.xp=123;saveState()});for(const value of [[],{level:'A1',completed:null},{level:'Z9'},{level:'A1',testHistory:{}},{level:'A1',xp:-5},{level:'A1',srs:{bad:null}},{level:'A1',skills:{grammar:'bad'}},{level:'A1',chatThreads:{bad:{}}}]){await page.evaluate(value=>importProgressFile({text:async()=>JSON.stringify({state:value})}),value);assert(await page.evaluate(()=>state.xp===123&&JSON.parse(localStorage.getItem('ne2_state')).xp===123))}console.log('PASS eight invalid backups preserve progress');
 await page.evaluate(()=>{const orig=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ne2_state')throw new DOMException('Full','QuotaExceededError');return orig.call(this,k,v)};try{saveState();navigate('course')}finally{Storage.prototype.setItem=orig}});assert(await page.locator('.course-map-v7').count());console.log('PASS storage quota preserves navigation');
 before=calls;await page.evaluate(()=>{startExamPart('writing','A1-A2');document.getElementById('examFreeV3').value='Jeg bor her.';submitExamProductive();submitExamProductive()});await page.waitForTimeout(1350);assert.equal(calls,before+1);assert((await page.locator('#app main').innerText()).includes('Задание 2/'));
 before=calls;await page.evaluate(()=>{const day=neLocalDate();state.dailyPacks[day]={date:day,level:'A1',practice:[{prompt_ru:'Расскажи',goal_ru:'Ответь',new_words:[],review_words:[]},{prompt_ru:'Далее',goal_ru:'Ответь',new_words:[],review_words:[]}]};startDailyPractice(day);document.getElementById('dailyAnswer').value='Jeg bor her.';checkDailyTask();checkDailyTask()});await page.waitForTimeout(950);assert.equal(calls,before+1);assert((await page.locator('#app main').innerText()).includes('2/2'));
 before=calls;await page.evaluate(()=>{navigate('storyside');document.getElementById('sideAnswer').value='Det er bra.';checkStorySide();checkStorySide()});await page.waitForTimeout(1100);assert.equal(calls,before+1);console.log('PASS exam, homework and side mission send once');
 const previous=await page.evaluate(()=>state.xp);const restored=await page.evaluate(()=>({...state,xp:321}));await page.evaluate(value=>importProgressFile({text:async()=>JSON.stringify({state:value})}),restored);await page.waitForTimeout(700);assert(await page.evaluate(x=>state.xp===321&&JSON.parse(localStorage.getItem('ne2_state_before_import')).xp===x,previous));console.log('PASS restore preserves prior backup');
 let cloudRequests=0,pushOk=true,pullOk=true;const remote=await page.evaluate(()=>({...state,wordFavorites:{remote:true},chatThreads:{'place:remote':[{role:'user',text:'Hei'}]},chatMemories:{'place:remote':[{role:'user',text:'Memory'}]}}));
 await page.route('**/api/cloud',async r=>{cloudRequests++;const body=r.request().postDataJSON();await new Promise(x=>setTimeout(x,100));await r.fulfill({json:body.name.endsWith('_pull')?{ok:pullOk,state:remote,revision:2}:{ok:pushOk,revision:3,error:pushOk?undefined:'DENIED'}})});
 await page.evaluate(()=>{localStorage.setItem('ne_cloud_link',JSON.stringify({sync_id:'qa-existing',secret:'qa-secret'}));state.wordFavorites={local:true};navigate('cloud')});const result=await page.evaluate(async()=>{const a=cloudSync();const b=cloudSync();navigate('course');return Promise.all([a,b])});assert.deepEqual(result,[true,false]);assert.equal(cloudRequests,2);assert(await page.evaluate(()=>state.wordFavorites.remote&&state.wordFavorites.local&&state.chatThreads['place:remote'].length&&state.chatMemories['place:remote'].length));assert(await page.locator('.course-map-v7').count());pushOk=false;assert.equal(await page.evaluate(()=>cloudSync(false)),false);pullOk=false;await page.evaluate(()=>{navigate('cloud');const e=document.createElement('textarea');e.id='cloudCode';e.value='bad.bad';document.body.appendChild(e)});await page.evaluate(()=>connectCloud());assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('ne_cloud_link')).sync_id==='qa-existing'));await page.evaluate(()=>localStorage.removeItem('ne_cloud_link'));console.log('PASS cloud preservation, serialized requests and rejected connection');
 for(const level of ['A1','A2','B1','B2']){await page.evaluate(level=>navigate('course',level),level);assert.equal(await page.locator('.near-lesson-v7').count(),await page.evaluate(()=>lessons(state.level).length))}
 for(const width of [360,390,768]){await page.setViewportSize({width,height:844});for(const screen of ['welcome','home','course','chat','story','learnedwords','lesson','listeninglab','grammarlab','exam','progress','settings']){await page.evaluate(screen=>navigate(screen,screen==='lesson'?'a1-1':undefined),screen);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),screen+' '+width)}}console.log('PASS every core lesson and 12 screens at three widths');
 await page.evaluate(()=>{window.confirm=()=>true;resetProgress()});await page.waitForTimeout(700);assert(await page.evaluate(()=>state.xp===0&&!!state.elite&&!!state.skills&&!!state.story&&!localStorage.getItem('ne_cloud_link')&&!!localStorage.getItem('ne2_state_before_reset')));assert.deepEqual(errors,[]);console.log('PASS reset reinitializes modules; zero browser errors');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
