const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');let phase=0;const originals=new Map();
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;
 if(name.startsWith('/api/')){let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw||'{}');res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(name.endsWith('session')&&body.action?{status:'approved',access_granted:true,owner:true,user_id:'11111111-1111-4111-8111-111111111111',email:'owner@example.com'}:name.endsWith('session')?{token:'qa'}:{score:90,accepted:true,reply_no:'Hei!',explanation_ru:'Хорошо'}))}
 const file=name==='/'?'index.html':name.slice(1);
 try{let data;if(phase===0){if(!originals.has(file))originals.set(file,execFileSync('git',['show','814132308d70ae2f4ed4ea4e823c48e58c075414:'+file],{cwd:root,maxBuffer:8*1024*1024,stdio:['ignore','pipe','ignore']}));data=originals.get(file)}else{data=fs.readFileSync(path.join(root,file));if(file==='sw.js'&&phase===2)data=Buffer.from(data.toString().replace('v8-0-0-feedback-r2','v8-0-0-feedback-r2-next'))}
 res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(data)}catch{res.statusCode=404;res.end('not found')}
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({...(process.env.NE_CHROMIUM_PATH?{executablePath:process.env.NE_CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const origin='http://127.0.0.1:'+server.address().port;const users=[];const errors=[];
 const waitMs=12000;
 for(const xp of [45,88]){const context=await browser.newContext({serviceWorkers:'allow',viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);page.setDefaultTimeout(waitMs);page.setDefaultNavigationTimeout(waitMs);await page.waitForTimeout(800);await page.evaluate(ms=>Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(new Error('SERVICE_WORKER_READY_TIMEOUT')),ms))]),waitMs);await page.waitForFunction(()=>navigator.serviceWorker.controller&&typeof state!=='undefined',null,{timeout:waitMs});await page.evaluate(xp=>{state.xp=xp;saveState()},xp);users.push({context,page,xp})}
 phase=1;
 for(const {page,xp} of users){await page.reload();await page.waitForFunction(()=>typeof APP_VERSION!=='undefined'&&APP_VERSION==='8.0.0',null,{timeout:waitMs});await page.waitForSelector('#neUpdateNotice');assert.equal(await page.evaluate(()=>state.xp),xp)}console.log('PASS installed production 7.3.8 migrates to 8.0.0; independent user progress preserved');
 const first=users[0];await first.page.evaluate(()=>navigate('lesson','a1-1'));await first.page.locator('#dialogAnswer').fill('Jeg heter Ola.');await first.page.locator('#neUpdateNotice button').click();await first.page.waitForTimeout(500);assert.equal(await first.page.locator('#dialogAnswer').inputValue(),'Jeg heter Ola.');assert((await first.page.locator('#neUpdateText').innerText()).includes('Сначала закончи'));console.log('PASS update waits for exercise and preserves unsent answer');
 for(const {page,xp} of users){await page.evaluate(()=>navigate('home'));await Promise.all([page.waitForNavigation(),page.locator('#neUpdateNotice button').click()]);await page.waitForFunction(()=>typeof state!=='undefined',null,{timeout:waitMs});assert.equal(await page.evaluate(()=>state.xp),xp);assert(await page.evaluate(async()=>!!(await caches.keys()).find(x=>x==='norsk-eventyr-v8-0-0-feedback-r2')))}console.log('PASS two users accept one published update with separate progress');
 phase=2;const page=first.page;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update()});await page.waitForSelector('#neUpdateNotice');await page.evaluate(()=>navigate('home'));await Promise.all([page.waitForNavigation(),page.locator('#neUpdateNotice button').click()]);assert(await page.evaluate(async()=>!!(await caches.keys()).find(x=>x.endsWith('-next'))));console.log('PASS next update discovered without reinstall');
 await first.context.setOffline(true);await page.reload();await page.waitForSelector('#accessRetry');assert.equal(await page.locator('#app').isVisible(),false);await first.context.setOffline(false);await page.locator('#accessRetry').click();await page.waitForFunction(()=>typeof state!=='undefined',null,{timeout:waitMs});assert.equal(await page.evaluate(()=>state.xp),45);console.log('PASS offline cold start stays locked; progress survives reconnection');assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
