const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');let phase=0;const originals=new Map();
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;
 if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(name.endsWith('session')?{token:'qa'}:{score:90,accepted:true,reply_no:'Hei!',explanation_ru:'Хорошо'}))}
 const file=name==='/'?'index.html':name.slice(1);
 try{let data;if(phase===0){if(!originals.has(file))originals.set(file,execFileSync('git',['show','0990ad4:'+file],{cwd:root,maxBuffer:8*1024*1024,stdio:['ignore','pipe','ignore']}));data=originals.get(file)}else{data=fs.readFileSync(path.join(root,file));if(file==='sw.js'&&phase===2)data=Buffer.from(data.toString().replace('v7-2-1-safe-updates','v7-2-1-safe-updates-next'))}
 res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(data)}catch{res.statusCode=404;res.end('not found')}
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({...(process.env.NE_CHROMIUM_PATH?{executablePath:process.env.NE_CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const origin='http://127.0.0.1:'+server.address().port;const users=[];const errors=[];
 for(const xp of [45,88]){const context=await browser.newContext({serviceWorkers:'allow',viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForTimeout(800);await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller&&typeof state!=='undefined');await page.evaluate(xp=>{state.xp=xp;saveState()},xp);users.push({context,page,xp})}
 phase=1;
 for(const {page,xp} of users){await page.reload();await page.waitForFunction(()=>typeof APP_VERSION!=='undefined'&&APP_VERSION==='7.2.1');await page.waitForSelector('#neUpdateNotice');assert.equal(await page.evaluate(()=>state.xp),xp)}console.log('PASS installed 7.2 migrates to 7.2.1; independent user progress preserved');
 const first=users[0];await first.page.evaluate(()=>navigate('lesson','a1-1'));await first.page.locator('#dialogAnswer').fill('Jeg heter Petro.');await first.page.locator('#neUpdateNotice button').click();await first.page.waitForTimeout(500);assert.equal(await first.page.locator('#dialogAnswer').inputValue(),'Jeg heter Petro.');assert((await first.page.locator('#neUpdateText').innerText()).includes('Сначала закончи'));console.log('PASS update waits for exercise and preserves unsent answer');
 for(const {page,xp} of users){await page.evaluate(()=>navigate('home'));await Promise.all([page.waitForNavigation(),page.locator('#neUpdateNotice button').click()]);await page.waitForFunction(()=>typeof state!=='undefined');assert.equal(await page.evaluate(()=>state.xp),xp);assert(await page.evaluate(async()=>!!(await caches.keys()).find(x=>x==='norsk-eventyr-v7-2-1-safe-updates')))}console.log('PASS two users accept one published update with separate progress');
 phase=2;const page=first.page;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update()});await page.waitForSelector('#neUpdateNotice');await page.evaluate(()=>navigate('home'));await Promise.all([page.waitForNavigation(),page.locator('#neUpdateNotice button').click()]);assert(await page.evaluate(async()=>!!(await caches.keys()).find(x=>x.endsWith('-next'))));console.log('PASS next update discovered without reinstall');
 await first.context.setOffline(true);await page.reload();await page.waitForFunction(()=>typeof state!=='undefined');assert.equal(await page.evaluate(()=>state.xp),45);for(const route of ['home','course','learnedwords','grammarlab','settings']){await page.evaluate(route=>navigate(route),route);assert(await page.locator('main').innerText())}console.log('PASS offline reload after update and five local screens');assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
